[package]
name = "dtools"
version = "0.1.0"
authors = ["David Alber <alber.david@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
rand = "0.6.5"

[dev-dependencies]
permutohedron = "0.2.4"
